# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool: 'Linux'
strategy:
  matrix:
    Python38:
      python.version: '3.8.2'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install pyyaml
    npm install --save-dev semantic-release
  displayName: 'Install dependencies'

- script: |
    python bookmark_generator.py example.yml > example.html
    cat example.html
    npx semantic-release
  env:
    GH_TOKEN: $(GH_TOKEN)
  displayName: 'Generate bookmark file'

